"""
Configuration package for the prototyping application.
Contains constants and configuration values.
"""

from .constants import (
    # Mode names
    MODE_PROGRESSION,
    MODE_COMPARISON,
    
    # UI labels - Compare Mode
    COMPARE_MODE_HEADER,
    COMPARE_MODE_UPLOAD_TOGGLE,
    COMPARE_MODE_SELECT_TOGGLE,
    COMPARE_MODE_ANALYSIS_TOGGLE,
    COMPARE_MODE_EXPORT_TOGGLE,
    
    # UI labels - Progression Mode
    PROGRESSION_MODE_HEADER,
    PROGRESSION_MODE_UPLOAD_TOGGLE,
    PROGRESSION_MODE_SELECT_TOGGLE,
    PROGRESSION_MODE_ANALYSIS_TOGGLE,
    PROGRESSION_MODE_EXPORT_TOGGLE,
    
    # Messages
    MSG_UPLOAD_DOCUMENT,
    MSG_SELECT_DOCUMENTS,
    MSG_ANALYSIS_STARTED,
    MSG_EXPORT_PDF,
    
    # Article upload labels
    LABEL_REFERENCE_DATE,
    LABEL_SOURCE,
    LABEL_ASSETS,
    LABEL_COMMODITIES,
    LABEL_MARKETS,
    LABEL_FORMAT,
    LABEL_TITLE,
    LABEL_TEXT_INPUT,
    LABEL_PDF_UPLOAD,
    
    # Button labels
    BTN_ADD_DOCUMENT,
    BTN_SAVE_ARTICLE,
    BTN_COMMIT_SELECTION,
    
    # Status messages
    MSG_FILE_UPLOADED,
    MSG_ARTICLE_SAVED,
    ERR_NO_TEXT,
    ERR_NO_PDF,
    
    # Data options
    ARTICLE_SOURCES,
    ARTICLE_FORMATS,
)

__all__ = [
    'MODE_PROGRESSION',
    'MODE_COMPARISON',
    'COMPARE_MODE_HEADER',
    'COMPARE_MODE_UPLOAD_TOGGLE',
    'COMPARE_MODE_SELECT_TOGGLE',
    'COMPARE_MODE_ANALYSIS_TOGGLE',
    'COMPARE_MODE_EXPORT_TOGGLE',
    'PROGRESSION_MODE_HEADER',
    'PROGRESSION_MODE_UPLOAD_TOGGLE',
    'PROGRESSION_MODE_SELECT_TOGGLE',
    'PROGRESSION_MODE_ANALYSIS_TOGGLE',
    'PROGRESSION_MODE_EXPORT_TOGGLE',
    'MSG_UPLOAD_DOCUMENT',
    'MSG_SELECT_DOCUMENTS',
    'MSG_ANALYSIS_STARTED',
    'MSG_EXPORT_PDF',
    'LABEL_REFERENCE_DATE',
    'LABEL_SOURCE',
    'LABEL_ASSETS',
    'LABEL_COMMODITIES',
    'LABEL_MARKETS',
    'LABEL_FORMAT',
    'LABEL_TITLE',
    'LABEL_TEXT_INPUT',
    'LABEL_PDF_UPLOAD',
    'BTN_ADD_DOCUMENT',
    'BTN_SAVE_ARTICLE',
    'BTN_COMMIT_SELECTION',
    'MSG_FILE_UPLOADED',
    'MSG_ARTICLE_SAVED',
    'ERR_NO_TEXT',
    'ERR_NO_PDF',
    'ARTICLE_SOURCES',
    'ARTICLE_FORMATS',
]
