"""
Configuration package for the prototyping application.
Contains constants and configuration values.
"""


from .constants import (
    # Mode names
    MODE_PROGRESSION,
    MODE_COMPARISON,
    MODE_NONE,
    
    # UI Headers
    WELCOME_HEADER,
    COMPARE_MODE_HEADER,
    PROGRESSION_MODE_HEADER,
    
    # UI labels - Compare Mode
    COMPARE_MODE_UPLOAD_TOGGLE,
    COMPARE_MODE_SELECT_TOGGLE,
    COMPARE_MODE_ANALYSIS_TOGGLE,
    COMPARE_MODE_EXPORT_TOGGLE,
    
    # UI labels - Progression Mode
    PROGRESSION_MODE_UPLOAD_TOGGLE,
    PROGRESSION_MODE_SELECT_TOGGLE,
    PROGRESSION_MODE_ANALYSIS_TOGGLE,
    PROGRESSION_MODE_EXPORT_TOGGLE,
    
    # General Status Messages
    LABEL_SELECT_ANALYSIS_MODE,
    MSG_UPLOAD_DOCUMENT,
    MSG_SELECT_DOCUMENTS,
    MSG_ANALYSIS_STARTED,
    MSG_EXPORT_PDF,
    
    # Button labels
    BTN_ADD_DOCUMENT,
    
    # Status messages
    MSG_FILE_UPLOADED,
    MSG_ARTICLE_SAVED,
    ERR_NO_TEXT,
    ERR_NO_PDF,
)


__all__ = [
    'MODE_PROGRESSION',
    'MODE_COMPARISON',
    'MODE_NONE',
    'WELCOME_HEADER',
    'COMPARE_MODE_HEADER',
    'PROGRESSION_MODE_HEADER',
    'COMPARE_MODE_UPLOAD_TOGGLE',
    'COMPARE_MODE_SELECT_TOGGLE',
    'COMPARE_MODE_ANALYSIS_TOGGLE',
    'COMPARE_MODE_EXPORT_TOGGLE',
    'PROGRESSION_MODE_UPLOAD_TOGGLE',
    'PROGRESSION_MODE_SELECT_TOGGLE',
    'PROGRESSION_MODE_ANALYSIS_TOGGLE',
    'PROGRESSION_MODE_EXPORT_TOGGLE',
    'LABEL_SELECT_ANALYSIS_MODE',
    'MSG_UPLOAD_DOCUMENT',
    'MSG_SELECT_DOCUMENTS',
    'MSG_ANALYSIS_STARTED',
    'MSG_EXPORT_PDF',
    'BTN_ADD_DOCUMENT',
    'MSG_FILE_UPLOADED',
    'MSG_ARTICLE_SAVED',
    'ERR_NO_TEXT',
    'ERR_NO_PDF',
]
